### ISSUE TITLE
[APA] FPWD Request for <Requirements for Personalization Semantics>

### ISSUE THREAD

**Issue by ruoxiran** [w3c/transitions#212]
# Document title, URLs, estimated publication date
[Document title: Requirements for Personalization Semantics
URI for transition review: [https://raw.githack.com/w3c/personalization-semantics/Wide-Review-Module1-WD-explainer-FPWD-requirement-20200128/snapshot/requirements/Overview.html](https://raw.githack.com/w3c/personalization-semantics/Wide-Review-Module1-WD-explainer-FPWD-requirement-20200128/snapshot/requirements/Overview.html)
Proposed shortname: personalization-semantics-requirements-1.0
Estimated publication date: Thursday, 30 January 2020]

# Abstract
[This is a requirements document for Personalization Semantics, this document contains use cases, requirements and user stories for personalization semantics.]

# Status
[This document was published by the [Accessible Platform Architectures Working Group](<https://www.w3.org/WAI/APA/) as a First Public Working Draft. This document contains use cases, requirements and user stories for personalization semantics.

To comment, file an issue in the W3C [personalization semantics GitHub repository](https://github.com/w3c/personalization-semantics/issues/new). If this is not feasible, send email to public-personalization-tf@w3.org ([archives](https://lists.w3.org/Archives/Public/public-personalization-tf/)). Comments are requested by 10 March 2020. In-progress updates to the document may be viewed in the publicly visible [editors' draft](https://w3c.github.io/personalization-semantics/requirements/).

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any [patent disclosures]( https://www.w3.org/2004/01/pp-impl/83907/status) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 March 2019 W3C Process Document.]

# Is it a delta specification intended to become a W3C Recommendation?
[no]

# Link to group's decision to request transition
[https://lists.w3.org/Archives/Public/public-apa-admin/2020Jan/0014.html]

# Information about implementations known to the Working Group
[This is a requirement document to support personalization semantics. For personalization semantics, there is a wiki page showing implementations, see in [implementations wiki](https://github.com/w3c/personalization-semantics/wiki/Implementations-of-Semantics).]

**Comment by plehegar** [comment]
Transition approved if the following change is made: Per [charter](https://www.w3.org/2018/08/apa-charter#licensing), the W3C Software and Document license for Note-track deliverables and licensed non-TR publications shall be used. Update the license associated with this document to reflect the proper license.

**Comment by ruoxiran** [comment]
> Transition approved if the following change is made: Per [charter](https://www.w3.org/2018/08/apa-charter#licensing), the W3C Software and Document license for Note-track deliverables and licensed non-TR publications shall be used. Update the license associated with this document to reflect the proper license.

Thank you for your review, now I fixed the issue, 
best.

**Comment by plehegar** [comment]
Looking at
 https://www.w3.org/TR/2020/WD-personalization-semantics-requirements-1.0-20200130/

The issue raised was NOT fixed. I still see https://www.w3.org/Consortium/Legal/2015/doc-license in use there while it's supposed to use https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

**Comment by ruoxiran** [comment]
> Looking at
> https://www.w3.org/TR/2020/WD-personalization-semantics-requirements-1.0-20200130/
> 
> The issue raised was NOT fixed. I still see https://www.w3.org/Consortium/Legal/2015/doc-license in use there while it's supposed to use https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

I modified the license parameter in respec.js and regenerated snapshot, it didn't seem to work. I fix the link now, sorry for that.

**Comment by plehegar** [comment]
Not sure what you fixed but I couldn't find it.

You now got a pull request from me:
 https://github.com/w3c/personalization-semantics/pull/134

**Comment by ruoxiran** [comment]
I previously modified this parameter from licence: "document" to "w3c-software" instead of removed it in branch, now I see. And TR document[1] has been fixed yesterday. Thank you.

[1] https://www.w3.org/TR/2020/WD-personalization-semantics-requirements-1.0-20200130/

**Comment by plehegar** [comment]
thank you
